name: ble_devtools_extension
description: Flutter web DevTools panel for inspecting BLE traces.
publish_to: none
version: 0.1.0
repository: https://github.com/sonigeez/flutter-ble-devtools
environment:
  sdk: ^3.4.0
  flutter: '>=3.24.0'
dependencies:
  ble_devtools_core: ^0.1.0
  devtools_extensions: ^0.5.1
  file_selector: ^1.0.4
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
flutter:
  uses-material-design: true
